UPSTREAM: <carry>: add replace for k8s.io/endpointslice module
Can be dropped if upstream adds this replace to go.mod:

k8s.io/endpointslice => k8s.io/endpointslice v0.29.0

Reported upstream: kubernetes-sigs#2008

Commit fixes verify-deps check which was failing with:

go: k8s.io/endpointslice@v0.0.0: invalid version: unknown revision v0.0.0
ERROR: go list -mod=readonly -m all failed with the message listed above.
Cachito used in ART builds will fail to resolve dependencies offline.
Typically, a pinned version is missing in go.mod, e.g.:
    replace k8s.io/foo => k8s.io/foo v0.26.0